#!/usr/bin/env bash
# install neovim if not installed
if ! command -v nvim &> /dev/null
then
    # install vim plug
    sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
           https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    case "$(uname -s)" in

   Darwin)
     echo 'Using Mac OS X install with brew'
     brew install nvim --HEAD
     ;;

   Linux)
     echo 'Linux'
     git clone https://github.com/neovim/neovim ~/neovim
     cd ~/neovim
     sudo apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip
     make CMAKE_BUILD_TYPE=Release
     sudo make install
     ;;

   CYGWIN*|MINGW32*|MSYS*|MINGW*)
     echo 'MS Windows'
     ;;

   # Add here more strings to compare
   # See correspondence table at the bottom of this answer

   *)
     echo 'Other OS' 
     ;;
    esac
else
    echo "nvim already installed"
fi

if command -v python3 &> /dev/null
then
    pip3 install neovim
    pip3 install 'python-language-server[all]'
fi

# Make nvim directories
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua

# link wholesale
for f in `find . -regex ".*\.vim$"`; do
    rm -rf ~/.config/nvim/$f
    ln -s ~/dotfiles/mike_neovim/$f ~/.config/nvim/$f
done
for f in `find . -regex ".*\.lua$"`; do
    rm -rf ~/.config/nvim/$f
    ln -s ~/dotfiles/mike_neovim/$f ~/.config/nvim/$f
done

