#!/usr/bin/env bash
# install neovim if not installed
if ! command -v nvim &> /dev/null
then
    case "$(uname -s)" in

   Darwin)
     echo 'Using Mac OS X install with brew'
     brew install nvim --HEAD
     ;;

   Linux)
     echo 'Linux'
     ;;

   CYGWIN*|MINGW32*|MSYS*|MINGW*)
     echo 'MS Windows'
     ;;

   # Add here more strings to compare
   # See correspondence table at the bottom of this answer

   *)
     echo 'Other OS'
     ;;
    esac
else
    echo "nvim already installed"
fi

# Make nvim directories
mkdir -p $XDG_CONFIG_HOME/nvim/plugin
mkdir -p $XDG_CONFIG_HOME/nvim/after/plugin
mkdir -p $XDG_CONFIG_HOME/nvim/lua
mkdir -p $XDG_CONFIG_HOME/nvim/lua/mike

# link wholesale
for f in `find . -regex ".*\.vim$"`; do
    rm -rf $XDG_CONFIG_HOME/nvim/$f
    ln -s $DOTFILES/mike_neovim/$f $XDG_CONFIG_HOME/nvim/$f
done
for f in `find . -regex ".*\.lua$"`; do
    rm -rf $XDG_CONFIG_HOME/nvim/$f
    ln -s $DOTFILES/mike_neovim/$f $XDG_CONFIG_HOME/nvim/$f
done

rm $XDG_CONFIG_HOME/tmux/tmux.conf
ln -s $DOTFILES/mike_neovim/.tmux.conf $XDG_CONFIG_HOME/tmux/tmux.conf
