#!/usr/bin/env bash
# install neovim if not installed
if ! command -v nvim &> /dev/null
then
    brew install nvim
    # install vim plug
    sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
           https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
else
    echo "nvim already installed"
fi



# Make nvim directories
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua

# link wholesale
for f in `find . -regex ".*\.vim$"`; do
    rm -rf ~/.config/nvim/$f
    ln -s ~/dotfiles/mike_neovim/$f ~/.config/nvim/$f
done
for f in `find . -regex ".*\.lua$"`; do
    rm -rf ~/.config/nvim/$f
    ln -s ~/dotfiles/mike_neovim/$f ~/.config/nvim/$f
done

